=== AppleGamerOfficial/Funkin-REGAN/schemas/stage.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://raw.githubusercontent.com/zatrit/Funkin-REGEN-ext/master/schemas/stage.json",
    "title": "REGEN stage",
    "items": {"properties": {
        "name":{
            "type":"string",
            "description": "Stage name",
            "default":"stage"
        },
        "camZoom":{
            "type":"number",
            "minimum": 0,
            "description": "Camera Zoom",
            "default":"0.9"
        },
        "library":{
            "type":"string",
            "description": "Assets library",
            "default":"shared"
        },
        "objects":{
            "type":"array",
            "description": "Array of objects",
            "required":["name","map","position","defaultAnimation","animations"],
            "additionalItems": {
                "properties": {
                    "name":{
                        "description": "Object name",
                        "type":"string"
                    },
                    "map":{
                        "description": "Add to objects map",
                        "type":"boolean",
                        "default":"false"
                    },
                    "position":{
                        "type":"array",
                        "default":["0","0"]
                    },
                    "defaultAnimation":{
                        "default":"",
                        "type":"string"
                    },
                    "animations":{
                        "description": "Animation",
                        "type":"array",
                        "additionalItems": {
                            "properties": {
                                "fps":{
                                    "type":"integer",
                                    "default":"24",
                                    "description": "Framerate of animation"
                                },
                                "prefix":{
                                    "type":"string",
                                    "description": "Animation prefix"
                                },
                                "name":{
                                    "type":"string",
                                    "description": "Animation name"
                                }
                            }
                        },
                        "required":["fps","prefix","name"]
                    }
                }
            }
        }
    }},
   "required": ["name", "camZoom", "library","objects"]
}

=== AppleGamerOfficial/Funkin-REGAN/assets/preload/data/spookeez/stage.json
{
   "$schema": "https://raw.githubusercontent.com/zatrit/Funkin-REGEN-ext/master/schemas/stage.json",
   "camZoom": 1.05,
   "library": "week2",
   "name": "stage",
   "objects": [
      {
         "defaultAnimation":"",
         "active": false,
         "animations": [
            {
               "name": "idle",
               "fps": 24,
               "loop": false,
               "prefix": "halloweem bg0"
            },
            {
               "name": "lightning",
               "fps": 24,
               "loop": false,
               "prefix": "halloweem bg lightning strike"
            }
         ],
         "name": "halloweenBG",
         "position": {"x": -200,"y": -100},
         "scrollFactor": {"x": 0.9,"y": 0.9},
         "map": true,
         "scale": {
             "x": 1.1,
             "y": 1.1
         },
         "file":"halloween_bg"
      }
   ]
}

=== AppleGamerOfficial/Funkin-REGAN/assets/preload/data/stage.json
{
   "$schema": "https://raw.githubusercontent.com/zatrit/Funkin-REGEN-ext/master/schemas/stage.json",
   "camZoom": 0.9,
   "library": "shared",
   "name": "stage",
   "objects": [
      {
         "defaultAnimation":"",
         "active": false,
         "animations": [],
         "name": "bg",
         "position": {"x": -600,"y": -200},
         "scrollFactor": {"x": 0.9,"y": 0.9},
         "map": false,
         "scale": {
             "x": 1.1,
             "y": 1.1
         },
         "file":"stageback"
      },
      {
         "defaultAnimation":"",
         "active": false,
         "animations": [],
         "name": "stageFront",
         "position": {"x": -650,"y": 600},
         "scrollFactor": {"x": 0.9,"y": 0.9},
         "map": false,
         "scale": {
             "x": 1.1,
             "y": 1.1
         },
         "file":"stagefront"
      },
      {
         "defaultAnimation":"",
         "active": false,
         "animations": [],
         "name": "stageCurtains",
         "position": {"x": -500,"y": -300},
         "scrollFactor": {"x": 1.3,"y": 1.3},
         "map": false,
         "scale": {
             "x": 0.9,
             "y": 0.9
         },
         "file":"stagecurtains"
      }
   ]
}

=== AppleGamerOfficial/Funkin-REGAN/assets/preload/data/flatzone/stage.json
{
   "$schema": "https://raw.githubusercontent.com/zatrit/Funkin-REGEN-ext/master/schemas/stage.json",
   "camZoom": 1.05,
   "library": "g3wWeek",
   "name": "gas",
   "objects": [
      {
         "active": false,
         "animations": [],
         "name": "bg",
         "position": {"x": -200,"y": -100},
         "scrollFactor": {"x":1,"y":1},
         "map": false,
         "scale": {
             "x": 1,
             "y": 1
         },
         "file":"gas_bg"
      }
   ]
}
